language: android
dist: trusty
android:
    components:
        - build-tools-28.0.3
        - build-tools-28.0.1
        - android-28
        - add-on
        - extra
        - platform-tools
        - tools

